service: react-pusher-chat-app

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  pusher:
    handler: src/pusher.execute
    environment:
      STAGE: ${env:STAGE}
    events:
      - http:
          path: /pusher
          method: post

plugins:
  - serverless-plugin-typescript
